version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: my-key
      MINIO_SECRET_KEY: my-password-key
    command: server /data

  conversion-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: my-key
      MINIO_SECRET_KEY: my-password-key
