spring:
  application:
    name: conversion-microservice

minio:
  endpoint: http://localhost:9000
  access-key: my-key
  secret-key: my-password-key
  bucket: my-bucket

logging:
  level:
    root: INFO
    com.example: DEBUG

server:
  port: 8080